version: "3.7"

services:
  botvid:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: botvid
    network_mode: host
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    environment:
      - API_KEY=
      - ALLOWED_IDS=
      - USER_ID=
      - USER_KEY=
    volumes:
      - ./botvid/opt/dockerbot/:/opt/dockerbot/
